/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as CreateTemplateIdRouteImport } from './routes/create.$templateId'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as TemplatesIdRouteImport } from './routes/templates.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateTemplateIdRoute = CreateTemplateIdRouteImport.update({
  id: '/create/$templateId',
  path: '/create/$templateId',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesIdRoute = TemplatesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TemplatesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/templates': typeof TemplatesRouteWithChildren
  '/create/$templateId': typeof CreateTemplateIdRoute
  '/p/$slug': typeof PSlugRoute
  '/templates/$id': typeof TemplatesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/templates': typeof TemplatesRouteWithChildren
  '/create/$templateId': typeof CreateTemplateIdRoute
  '/p/$slug': typeof PSlugRoute
  '/templates/$id': typeof TemplatesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/templates': typeof TemplatesRouteWithChildren
  '/create/$templateId': typeof CreateTemplateIdRoute
  '/p/$slug': typeof PSlugRoute
  '/templates/$id': typeof TemplatesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/templates' | '/create/$templateId' | '/p/$slug' | '/templates/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/templates' | '/create/$templateId' | '/p/$slug' | '/templates/$id'
  id:
    | '__root__'
    | '/'
    | '/templates'
    | '/create/$templateId'
    | '/p/$slug'
    | '/templates/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TemplatesRoute: typeof TemplatesRouteWithChildren
  CreateTemplateIdRoute: typeof CreateTemplateIdRoute
  PSlugRoute: typeof PSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/$templateId': {
      id: '/create/$templateId'
      path: '/create/$templateId'
      fullPath: '/create/$templateId'
      preLoaderRoute: typeof CreateTemplateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/$id': {
      id: '/templates/$id'
      path: '/$id'
      fullPath: '/templates/$id'
      preLoaderRoute: typeof TemplatesIdRouteImport
      parentRoute: typeof TemplatesRoute
    }
  }
}

interface TemplatesRouteChildren {
  TemplatesIdRoute: typeof TemplatesIdRoute
}

const TemplatesRouteChildren: TemplatesRouteChildren = {
  TemplatesIdRoute: TemplatesIdRoute,
}

const TemplatesRouteWithChildren = TemplatesRoute._addFileChildren(
  TemplatesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TemplatesRoute: TemplatesRouteWithChildren,
  CreateTemplateIdRoute: CreateTemplateIdRoute,
  PSlugRoute: PSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
